DROP TABLE user IF EXISTS;

CREATE TABLE user (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
  username VARCHAR(40),
  name     VARCHAR(40),
  age      INT,
  balance  DECIMAL(10, 2),
  PRIMARY KEY (id)
);